# @package _global_

trainer: trainers.pi3_trainer.Pi3Trainer

train:
  image_num_range: [2, 12]     # hres
  max_img_per_gpu: 12             # hres

  # dynamic resolution and 
  random_reslution: true
  aspect_ratio_range: [0.5, 2.0]
  pixel_count_range: [100000, 255000] 
  patch_size: 56
  num_resolution: -1
